services:
  frontend-nginx:
    image: ghcr.io/du-css/frontend-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/certs
    network_mode: host

  frontend-node:
    image: ghcr.io/du-css/frontend-node:latest
    network_mode: host
    depends_on:
      - backend
      - frontend-nginx 

  #frontend-provisional:
  #  image: ghcr.io/du-css/frontend-provisional:latest
  #  network_mode: host
  #  depends_on:
  #    - backend
  #    - frontend-nginx

  backend:
    image: ghcr.io/du-css/backend:latest
    network_mode: host
    environment:
      - STRIPE_API_KEY=${STRIPE_API_KEY}
