services:
  frontend-nginx:
    image: ghcr.io/du-css/frontend-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/certs
    networks:
      - internal
  # frontend-node:
    # image: ghcr.io/du-css/frontend-node:latest
    # networks:
      # - internal
  frontend-provisional:
    image: ghcr.io/du-css/frontend-provisional:latest
    networks:
      - internal
    depends_on:
      - backend
      - frontend-nginx
  backend:
    image: ghcr.io/du-css/backend:latest
    networks:
      - internal
    environment:
      - STRIPE_API_KEY=${STRIPE_API_KEY}


networks:
  internal:
    driver: bridge