version: "3"

services:
  frontend-node:
    container_name: frontend-node
    image: ghcr.io/du-css/frontend-node:latest
    user: "node"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  frontend-nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ducss_frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./cerbot/www:/var/www/certbot
#
#  backend:
#    image: ghcr.io/du-css/backend:latest
#    restart: unless-stopped
#    environment:
#      - STRIPE_API_KEY=${STRIPE_API_KEY}
#
#  certbot:
#    image: certbot/certbot    
#    container_name: certbot
#    restart: unless-stopped
#    volumes:
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot    
#    command: certonly --webroot -w /var/www/certbot --force-renewal --email ducss@csc.tcd.ie -d ducss.ie --agree-tos
#    depends_on:
#      - frontend-node