services:
  frontend-nginx:
    image: ghcr.io/du-css/frontend-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/certs
    networks:
      - internal

  frontend-node:
    image: ghcr.io/du-css/frontend-node:latest
    networks:
      - internal

networks:
  internal:
    driver: bridge
