services:
  frontend-nginx:
    image: ghcr.io/du-css/frontend-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/certs
    networks:
      - internal

  frontend-node:
    image: ghcr.io/du-css/frontend-node:latest
    networks:
      - internal

  frontend-provisional:
    # image: ghcr.io/du-css/frontend-provisional:latest
    build:
      context: ./provisional-ducss-site
      dockerfile: Dockerfile
    networks:
      - internal

  backend:
    image: ghcr.io/du-css/backend:latest
    networks:
      - internal

networks:
  internal:
    driver: bridge
